syntax = "proto3";

option csharp_namespace = "DroneServer";

package drones;

service DroneService {
  // Auth & Users
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc RegisterUser (RegisterRequest) returns (RegisterResponse);
  rpc GetAllUsers (Empty) returns (UserList);
  rpc DeleteUser (UserRequest) returns (ServerResponse);

  // Orders
  rpc GetOrders (ClientRequest) returns (OrderList);
  rpc AddOrder (DroneOrderMsg) returns (ServerResponse);
  rpc UpdateOrder (DroneOrderMsg) returns (ServerResponse);
  rpc DeleteOrder (DeleteRequest) returns (ServerResponse);
}

message Empty {}

// --- Auth Messages ---

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  bool success = 1;
  string message = 2;
  string role = 3; // "Admin" or "User"
  string username = 4;
}

message RegisterRequest {
  string username = 1;
  string password = 2;
}

message RegisterResponse {
  bool success = 1;
  string message = 2;
}

message UserRequest {
  string username = 1;
}

message UserMsg {
  string username = 1;
  string role = 2;
}

message UserList {
  repeated UserMsg users = 1;
}

// --- Order Messages ---

message ClientRequest {
  string clientId = 1; // Teraz to będzie Username
  string role = 2;     // "Admin" lub "User" - dla filtrowania
}

message ClientInfo {
  string platform = 1;
}

message ClientReponse {
  string clientId = 1;
  bool success = 2;
}

message OrderList {
  repeated DroneOrderMsg orders = 1;
}

message DroneOrderMsg {
  string id = 1;
  string originAddress = 2;
  double originLat = 3;
  double originLng = 4;
  string destinationAddress = 5;
  double destLat = 6;
  double destLng = 7;
  double packageWeightKg = 8;
  string status = 9;
  double progress = 10;
  bool isIncoming = 11;
  string sendDate = 12;
  string deliveryDate = 13;
  double currentLat = 14;
  double currentLng = 15;
  string clientId = 16; // Właściciel paczki (Username)
}

message ServerResponse {
  bool success = 1;
  string message = 2;
}

message DeleteRequest {
  string id = 1;
  string clientId = 2;
}