syntax = "proto3";

option csharp_namespace = "DroneServer";

package drones;

service DroneService {
  // --- UŻYTKOWNICY ---
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc RegisterUser (RegisterUserRequest) returns (RegisterUserResponse);
  
  // NOWE: Zarządzanie użytkownikami
  rpc GetAllUsers (Empty) returns (UserList);
  rpc DeleteUser (UserRequest) returns (ServerResponse);

  // --- PACZKI ---
  rpc GetAllOrders (Empty) returns (OrderList); // Admin
  rpc UpdateOrderStatus (StatusRequest) returns (ServerResponse); // Admin
  
  rpc GetOrders (ClientRequest) returns (OrderList);
  rpc AddOrder (DroneOrderMsg) returns (ServerResponse);
  rpc UpdateOrder (DroneOrderMsg) returns (ServerResponse);
  rpc DeleteOrder (DeleteRequest) returns (ServerResponse);
  
  // Stare/Kompatybilność
  rpc RegisterClient (ClientInfo) returns (RegisterResponse);
}

message Empty {}

// --- WIADOMOŚCI UŻYTKOWNIKÓW ---
message LoginRequest { string username = 1; string password = 2; }
message LoginResponse { bool success = 1; string role = 2; string clientId = 3; string message = 4; }

message RegisterUserRequest { string username = 1; string password = 2; }
message RegisterUserResponse { bool success = 1; string message = 2; }

message UserList { repeated UserMsg users = 1; }
message UserMsg { int32 id = 1; string username = 2; string role = 3; }
message UserRequest { string username = 1; }

// --- WIADOMOŚCI PACZEK ---
message StatusRequest { string orderId = 1; string newStatus = 2; bool isAdmin = 3; }
message ClientInfo { string platform = 1; }
message RegisterResponse { bool success = 1; string clientId = 2; }
message ClientRequest { string clientId = 1; }
message DeleteRequest { string id = 1; string clientId = 2; }
message ServerResponse { bool success = 1; string message = 2; }
message OrderList { repeated DroneOrderMsg orders = 1; }

message DroneOrderMsg {
  string id = 1;
  string originAddress = 2;
  double originLat = 3;
  double originLng = 4;
  string destinationAddress = 5;
  double destLat = 6;
  double destLng = 7;
  double packageWeightKg = 8;
  string status = 9;
  double progress = 10;
  bool isIncoming = 11;
  string sendDate = 12;
  string deliveryDate = 13;
  double currentLat = 14;
  double currentLng = 15;
  string clientId = 16;
}