syntax = "proto3";

option csharp_namespace = "DroneServer";

package drones;

service DroneService {
  // Rejestracja klienta (hello)
  rpc RegisterClient (ClientInfo) returns (RegisterResponse);
  // Pobierz paczki danego klienta
  rpc GetOrders (ClientRequest) returns (OrderList);
  // Dodaj nową paczkę
  rpc AddOrder (DroneOrderMsg) returns (ServerResponse);
  // Zaktualizuj status (dron melduje pozycję)
  rpc UpdateOrder (DroneOrderMsg) returns (ServerResponse);
  // Usuń paczkę
  rpc DeleteOrder (DeleteRequest) returns (ServerResponse);
}

message Empty {}

// Informacje o kliencie przy rejestracji
message ClientInfo {
  string platform = 1;  // "Linux", "Mac", "Windows"
}

// Odpowiedź z przydzielonym ID klienta
message RegisterResponse {
  bool success = 1;
  string clientId = 2;  // np. "Linux1", "Mac2"
}

// Żądanie z identyfikatorem klienta
message ClientRequest {
  string clientId = 1;
}

message DeleteRequest {
  string id = 1;
  string clientId = 2;
}

message ServerResponse {
  bool success = 1;
  string message = 2;
}

message OrderList {
  repeated DroneOrderMsg orders = 1;
}

// To jest odpowiednik Twojego DroneOrder.cs
message DroneOrderMsg {
  string id = 1;
  string originAddress = 2;
  double originLat = 3;
  double originLng = 4;
  string destinationAddress = 5;
  double destLat = 6;
  double destLng = 7;
  double packageWeightKg = 8;
  string status = 9;
  double progress = 10;
  bool isIncoming = 11;
  string sendDate = 12;      // Daty przesyłamy jako tekst (ISO 8601)
  string deliveryDate = 13;
  double currentLat = 14;
  double currentLng = 15;
  string clientId = 16;      // ID klienta który utworzył paczkę
}